language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        packages:
            - cmake
            - libjsoncpp-dev
            - libcurl4-gnutls-dev
            - libncursesw5-dev
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make
