language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - clang
            - g++
            - libjsoncpp-dev
            - libcurl4-gnutls-dev
            - libncursesw5-dev
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make
