language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'ppa:h-rayflood/llvm'
        packages:
            - cmake
            - libjsoncpp-dev
            - libcurl4-gnutls-dev
            - libncursesw5-dev
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make
